runtime: python
env: flex
entrypoint: gunicorn --worker-class eventlet -w 1 app:app --timeout 120
runtime_config:
    python_version: 3
manual_scaling:
    instances: 1
network:
 session_affinity: true